<?php
  defined('DIR_FS_CATALOG_CATEGORIES_IMAGES') or define('DIR_FS_CATALOG_CATEGORIES_IMAGES', DIR_FS_CATALOG_IMAGES .'categories/');
  defined('DIR_FS_CATALOG_CATEGORIES_THUMBNAIL_IMAGES') or define('DIR_FS_CATALOG_CATEGORIES_THUMBNAIL_IMAGES', DIR_FS_CATALOG_CATEGORIES_IMAGES . 'thumbnail_images/');
  defined('DIR_FS_CATALOG_CATEGORIES_INFO_IMAGES') or define('DIR_FS_CATALOG_CATEGORIES_INFO_IMAGES', DIR_FS_CATALOG_CATEGORIES_IMAGES .'info_images/');
